project:
  app_name: Ecommerce Data Platform
  version: 1.0

spark:
  app_name: Ecommerce Data Platform
  master: local[*]

  config:
    spark.sql.shuffle.partitions: 8
    spark.sql.session.timezone: UTC
    spark.sql.adaptive.enabled: true
    spark.serializer: org.apache.spark.serializer.KryoSerializer

logging:
  level: INFO
  path: logs/
  file: etl.log

datasets:
  categories:
    enabled: false
    source: data/source/categories.csv
    bronze: data/bronze/categories
    silver: data/silver/categories
    gold: data/gold/dim_categories
    quarantine: data/quarantine/categories
    schema: categories_schema
    format: csv
    delimiter: ","
    header: true

  customers:
    enabled: true
    source: data/source/customers.csv
    bronze: data/bronze/customers
    silver: data/silver/customers
    gold: data/gold/dim_customers
    quarantine: data/quarantine/customers
    schema: customer_schema
    format: csv
    delimiter: ","
    header: true
    validation:
      mandatory_columns:
        - customer_id
        - first_name
        - email
      
      duplicate_keys:
        - customer_id
      
      max_bad_records_percent: 5

    transformations:
      - type: trim

      - type: email_normalizer
        column: email

      - type: date_normalizer
        columns:
          - signup_datetime
          - date_of_birth
          - last_modified_date

      - type: standardization
        mappings:
          gender:
            m: Male
            male: Male
            f: Female
            female: Female

  order_items:
    enabled: false
    source: data/source/order_items.csv
    bronze: data/bronze/order_items
    silver: data/silver/order_items
    gold: data/gold/dim_order_items
    quarantine: data/quarantine/order_items
    schema: order_items_schema
    format: csv
    delimiter: ","
    header: true

  orders:
    enabled: false
    source: data/source/orders.csv
    bronze: data/bronze/orders
    silver: data/silver/orders
    gold: data/gold/fact_orders
    quarantine: data/quarantine/orders
    schema: orders_schema
    format: csv
    delimiter: ","
    header: true

  products:
    enabled: false
    source: data/source/products.csv
    bronze: data/bronze/products
    silver: data/silver/products
    gold: data/gold/dim_products
    quarantine: data/quarantine/products
    schema: products_schema
    format: csv
    delimiter: ","
    header: true

  wishlist:
    enabled: false
    source: data/source/wishlist.csv
    bronze: data/bronze/wishlist
    silver: data/silver/wishlist
    gold: data/gold/dim_wishlist
    quarantine: data/quarantine/wishlist
    schema: wishlist_schema
    format: csv
    delimiter: ","
    header: true


file:
  format: csv
  delimiter: ","
  header: true

metadata:
  pipeline: Bronze
  owner: Amrit
  batch_size: 10000